#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
